warnings()
print("R script rinning")
install.packages("alakazam", repos='http://cran.us.r-project.org')
install.packages("tidyr", repos='http://cran.us.r-project.org')
install.packages("shazam", repos='http://cran.us.r-project.org')
install.packages("ggplot2", repos='http://cran.us.r-project.org')
install.packages("dplyr", repos='http://cran.us.r-project.org')
install.packages("doParallel", repos='http://cran.us.r-project.org')
install.packages("foreach", repos='http://cran.us.r-project.org')
install.packages("iterators", repos='http://cran.us.r-project.org')
install.packages("tigger_0.2.4.999.tar.gz", repos=NULL, type="source")
